'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const {candles,baseline,strategy,backtest,candidates,monthsBefore}=require('./strategy-lab.cjs');
const original=fs.readFileSync(path.join(__dirname,'original-app-v2.js'),'utf8');
function originalContext(){const src=original.slice(original.indexOf('const STRATEGY_CONFIGS ='),original.indexOf('\nif (localStorage'))+'\n'+original.slice(original.indexOf('function movingAverage('),original.indexOf('function formatBacktestRange('));const ctx={state:{product:'al',backtestDirection:'both',backtestPriceMode:'ideal',klineInterval:'1d'},isFiniteNumber:x=>typeof x==='number'&&Number.isFinite(x),isMaEnabled:p=>Number.isFinite(p)&&p>0,strategyLabel:k=>k,clamp:(v,a,b)=>Math.max(a,Math.min(b,v))};vm.createContext(ctx);vm.runInContext(src,ctx);return ctx;}
test('snapshot ordered unique finite; four legacy pre-training OHLC inconsistencies documented',()=>{let previous='';const anomalies=[];for(const c of candles){assert.ok(c.date>previous);previous=c.date;for(const k of ['open','high','low','close'])assert.ok(Number.isFinite(c[k])&&c[k]>0);if(c.high<Math.max(c.open,c.close,c.low)||c.low>Math.min(c.open,c.close,c.high))anomalies.push(c.date);}assert.deepEqual(anomalies,['2006-01-04','2006-12-06','2006-12-22','2007-03-27']);});
test('baseline signals exactly match original app and ideal return matches all four windows',()=>{const ctx=originalContext();for(const key of ['al_update_1','al_best_1']){const actual=baseline(candles,key),old=ctx.computeStrategy(candles,key);assert.equal(JSON.stringify(actual),JSON.stringify(old.signals.map(({index,type})=>({index,type}))));for(const n of [1,3,6,12]){const end=candles.at(-1).date,start=monthsBefore(end,n);ctx.state.backtestStart=start+'T00:00';ctx.state.backtestEnd=end+'T23:59';const expect=ctx.computeBacktest(candles,old);const result=backtest(candles,actual,start,end);assert.ok(Math.abs(result.return-expect.totalReturn)<1e-12);assert.equal(result.trades,expect.trades.length);}}});
test('all candidate signals are invariant to future bars',()=>{for(const config of candidates){const full=strategy(candles,config).signals;for(const len of [100,500,1500,4500,5100]){const prefix=strategy(candles.slice(0,len),config).signals;assert.deepEqual(prefix,full.filter(s=>s.index<len),JSON.stringify(config));}}});
test('next-open execution shifts each signal and excludes unavailable next bar',()=>{const c=[{date:'2026-01-01',open:100,high:200,low:50,close:150},{date:'2026-01-02',open:120,high:190,low:60,close:130},{date:'2026-01-03',open:110,high:180,low:70,close:140}];const signals=[{index:0,type:'buy'},{index:1,type:'sell'},{index:2,type:'buy'}];const actual=backtest(c,signals,'2026-01-01','2026-01-03','next_open');assert.equal(actual.trades,1);assert.equal(actual.tradeLog[0].entryPrice,120);assert.equal(actual.tradeLog[0].exitPrice,110);assert.ok(Math.abs(actual.return-(-1/12))<1e-12);});
test('periods start flat and open ending trade excluded from headline return',()=>{const c=[{date:'2026-01-01',open:100,high:110,low:90,close:100},{date:'2026-01-02',open:100,high:110,low:90,close:100}];const actual=backtest(c,[{index:0,type:'buy'}],'2026-01-02','2026-01-02');assert.equal(actual.trades,0);assert.equal(actual.openPosition,null);const opened=backtest(c,[{index:1,type:'buy'}],'2026-01-02','2026-01-02');assert.equal(opened.return,0);assert.ok(opened.openPosition);assert.ok(opened.markToMarketReturn>0);});

test('production candidate pure function exactly reproduces candidate 33',()=>{const {computeChannel20Strategy}=require('./candidate-channel.js');const actual=computeChannel20Strategy(candles);const research=strategy(candles,{family:'bollinger_close',period:20,multiplier:0.5});assert.deepEqual(actual.signals.map(({index,type})=>({index,type})),research.signals);for(const [name,key] of [['up','upper'],['mid','mid'],['low','lower']])assert.deepEqual(actual.lines.find(x=>x.name===name).values,research.lines[key]);});
